config/routes.rb
Jets.application.routes.draw do
  resources :climbing_routes
  root "jets/public#show"

  # The jets/public#show controller can serve static utf8 content out of the public folder.
  # Note, as part of the deploy process Jets uploads files in the public folder to s3
  # and serves them out of s3 directly. S3 is well suited to serve static assets.
  # More info here: https://rubyonjets.com/docs/extras/assets-serving/
  any "*catchall", to: "jets/public#show"
end

app/models/application_item.rb
class ApplicationItem < Dynomite::Item
end

app/models/climbing_route.rb
class ClimbingRoute < Dynomite::Item
  column :id, :route_name, :beta, :description
end

app/controllers/application_controller.rb
class ApplicationController < Jets::Controller::Base
end

app/controllers/climbing_routes_controller.rb
class ClimbingRoutesController < ApplicationController
  before_action :set_climbing_route, only: [:show, :edit, :update, :delete]

  # GET /climbing_routes
  def index
    @climbing_routes = ClimbingRoute.scan({})
  end

  # GET /climbing_routes/1
  def show
  end

  # GET /climbing_routes/new
  def new
    @climbing_route = ClimbingRoute.new
  end

  # GET /climbing_routes/1/edit
  def edit
  end

  # POST /climbing_routes
  def create
    @climbing_route = ClimbingRoute.new(climbing_route_params.as_json)

    if @climbing_route.replace
      if request.xhr?
        render json: {success: true, location: url_for(@climbing_route)}
      else
        redirect_to climbing_route_path(@climbing_route.id)
      end
    else
      render :new
    end
  end

  # PUT /climbing_routes/1
  def update
    if @climbing_route.update(climbing_route_params)
      if request.xhr?
        render json: {success: true, location: url_for(@climbing_route)}
      else
        redirect_to climbing_route_path(@climbing_route)
      end
    else
      render :edit
    end
  end

  # DELETE /climbing_routes/1
  def delete
    ClimbingRoute.delete(@climbing_route.id)
    if request.xhr?
      render json: {success: true}
    else
      redirect_to climbing_routes_path
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_climbing_route
    @climbing_route = ClimbingRoute.find(params[:id])
  end

  def climbing_route_params
    params.require(:climbing_route).permit(:id, :route_name, :beta, :description).reject{|_, v| v.blank?}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/climbing_routes_helper.rb
module ClimbingRoutesHelper
end

app/views/climbing_routes/_form.html.erb
<%= form_with(url: "/climbing_routes", method: :post) do |f| %>
  <%= f.fields_for(:climbing_route) do |form| %>
    <div class="field">
      <%= form.label :route_name %>
      <%= form.text_field :route_name, value: @climbing_route.route_name %>
    </div>

    <div class="field">
      <%= form.label :beta %>
      <%= form.text_field :beta, value: @climbing_route.beta %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description, value: @climbing_route.description %>
    </div>
  <% end %>
  <div class="actions">
    <%= hidden_field(:climbing_route, :id, :value => @climbing_route.id) %>
    <%= f.submit %>
  </div>
<% end %>

app/views/climbing_routes/edit.html.erb
<h1>Editing Climbing Route</h1>

<%= render 'form', climbing_route: @climbing_route %>

<%= link_to 'Show', "/climbing_routes/#{@climbing_route.id}" %> |
<%= link_to 'Back', climbing_routes_path %>

app/views/climbing_routes/index.html.erb
<h1>Climbing Routes</h1>

<table>
  <thead>
    <tr>
      <th>Route Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @climbing_routes.each do |climbing_route| %>
      <tr class="jets-element-to-delete">
        <td><%= climbing_route.route_name %></td>
        <td><%= link_to 'Show', "/climbing_routes/#{climbing_route.id}" %></td>
        <td><%= link_to 'Edit', edit_climbing_route_path(climbing_route.id) %></td>
        <td><%= link_to 'Destroy', "/climbing_routes/#{climbing_route.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Climbing Route', new_climbing_route_path %>

app/views/climbing_routes/new.html.erb
<h1>New Climbing Route</h1>

<%= render 'form', climbing_route: @climbing_route %>

<%= link_to 'Back', climbing_routes_path %>

app/views/climbing_routes/show.html.erb
<p>
  <strong>Route name:</strong>
  <%= @climbing_route.route_name %>
</p>

<p>
  <strong>Beta:</strong>
  <%= @climbing_route.beta %>
</p>

<p>
  <strong>Description:</strong>
  <%= @climbing_route.description %>
</p>

<%= link_to 'Edit', edit_climbing_route_path(@climbing_route.id) %> |
<%= link_to 'Back', climbing_routes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
  <title>Jets App</title>
  <%= javascript_pack_tag "application" %>
  <%= stylesheet_pack_tag "theme" %>
  <link rel="shortcut icon" href="<%= favicon_path %>">
</head>
<body>
<section class="starter">
  <div class="container">
    <div class="row">
      <div class="col-md-9 content-body">
        <% if @title %><h1><%= @title %></h1><% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</section>
</body>
</html>